
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 22 02:50:53 CET 2013
//----------------------------------------------------

package stupaq.cloudatlas.query.parser.QueryLanguage;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int _SYMB_18 = 20;
  public static final int _SYMB_17 = 19;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int _INTEGER_ = 34;
  public static final int _STRING_ = 33;
  public static final int _SYMB_30 = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int _SYMB_29 = 31;
  public static final int XIdent = 36;
  public static final int _SYMB_28 = 30;
  public static final int _SYMB_27 = 29;
  public static final int _SYMB_26 = 28;
  public static final int _SYMB_25 = 27;
  public static final int _SYMB_24 = 26;
  public static final int _SYMB_23 = 25;
  public static final int _SYMB_22 = 24;
  public static final int _SYMB_21 = 23;
  public static final int _SYMB_20 = 22;
  public static final int _DOUBLE_ = 35;
  public static final int _SYMB_19 = 21;

  /* non terminals */
  static final int XExpression8 = 19;
  static final int XExpression7 = 18;
  static final int XExpression = 11;
  static final int XExpression6 = 17;
  static final int XExpression5 = 16;
  static final int XExpression4 = 15;
  static final int XExpression3 = 14;
  static final int XBoolConst = 24;
  static final int XExpression2 = 13;
  static final int XExpression1 = 12;
  static final int XNullsOption = 9;
  static final int XOrderItem = 6;
  static final int XOrderClause = 5;
  static final int ListXOrderItem = 7;
  static final int XArithOpMultiply = 22;
  static final int XRelOp = 23;
  static final int ListXSelectItem = 3;
  static final int XStatement = 2;
  static final int XSelectItem = 10;
  static final int XProgram = 0;
  static final int ListXStatement = 1;
  static final int XOrderOption = 8;
  static final int XArithOpAdd = 21;
  static final int XWhereClause = 4;
  static final int ListXExpression = 20;
}

