package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class ArithExprMultiply extends XExpression {
  public final XExpression xexpression_1, xexpression_2;
  public final XArithOpMultiply xarithopmultiply_;

  public ArithExprMultiply(XExpression p1, XArithOpMultiply p2, XExpression p3) { xexpression_1 = p1; xarithopmultiply_ = p2; xexpression_2 = p3; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprMultiply) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprMultiply x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprMultiply)o;
      return this.xexpression_1.equals(x.xexpression_1) && this.xarithopmultiply_.equals(x.xarithopmultiply_) && this.xexpression_2.equals(x.xexpression_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.xexpression_1.hashCode())+this.xarithopmultiply_.hashCode())+this.xexpression_2.hashCode();
  }


}
