package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class ArithOpSubstract extends XArithOpAdd {

  public ArithOpSubstract() { }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XArithOpAdd.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithOpSubstract) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
