package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprVar extends XExpression {
  public final String xident_;

  public BasicExprVar(String p1) { xident_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprVar) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprVar x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprVar)o;
      return this.xident_.equals(x.xident_);
    }
    return false;
  }

  public int hashCode() {
    return this.xident_.hashCode();
  }


}
