package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class CondExprOr extends XExpression {
  public final XExpression xexpression_1, xexpression_2;

  public CondExprOr(XExpression p1, XExpression p2) { xexpression_1 = p1; xexpression_2 = p2; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprOr) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprOr x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprOr)o;
      return this.xexpression_1.equals(x.xexpression_1) && this.xexpression_2.equals(x.xexpression_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.xexpression_1.hashCode())+this.xexpression_2.hashCode();
  }


}
