package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XArithOpAdd implements java.io.Serializable {
  public abstract <R,A> R accept(XArithOpAdd.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithOpAdd p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithOpSubstract p, A arg);

  }

}
