package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class ArithOpMultiply extends XArithOpMultiply {

  public ArithOpMultiply() { }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XArithOpMultiply.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithOpMultiply) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
