package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprTrue extends XExpression {
  public final XBoolConst xboolconst_;

  public BasicExprTrue(XBoolConst p1) { xboolconst_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprTrue) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprTrue x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprTrue)o;
      return this.xboolconst_.equals(x.xboolconst_);
    }
    return false;
  }

  public int hashCode() {
    return this.xboolconst_.hashCode();
  }


}
