package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprString extends XExpression {
  public final String string_;

  public BasicExprString(String p1) { string_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprString) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprString x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprString)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
