package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class OrderItemCond extends XOrderItem {
  public final XExpression xexpression_;
  public final XOrderOption xorderoption_;
  public final XNullsOption xnullsoption_;

  public OrderItemCond(XExpression p1, XOrderOption p2, XNullsOption p3) { xexpression_ = p1; xorderoption_ = p2; xnullsoption_ = p3; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XOrderItem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderItemCond) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderItemCond x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderItemCond)o;
      return this.xexpression_.equals(x.xexpression_) && this.xorderoption_.equals(x.xorderoption_) && this.xnullsoption_.equals(x.xnullsoption_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.xexpression_.hashCode())+this.xorderoption_.hashCode())+this.xnullsoption_.hashCode();
  }


}
