package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class SelectItem extends XSelectItem {
  public final XExpression xexpression_;

  public SelectItem(XExpression p1) { xexpression_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XSelectItem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.SelectItem) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.SelectItem x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.SelectItem)o;
      return this.xexpression_.equals(x.xexpression_);
    }
    return false;
  }

  public int hashCode() {
    return this.xexpression_.hashCode();
  }


}
