package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class Statement extends XStatement {
  public final ListXSelectItem listxselectitem_;
  public final XWhereClause xwhereclause_;
  public final XOrderClause xorderclause_;

  public Statement(ListXSelectItem p1, XWhereClause p2, XOrderClause p3) { listxselectitem_ = p1; xwhereclause_ = p2; xorderclause_ = p3; }

  public <R,A> R accept(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.XStatement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.Statement) {
      stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.Statement x = (stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.Statement)o;
      return this.listxselectitem_.equals(x.listxselectitem_) && this.xwhereclause_.equals(x.xwhereclause_) && this.xorderclause_.equals(x.xorderclause_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listxselectitem_.hashCode())+this.xwhereclause_.hashCode())+this.xorderclause_.hashCode();
  }


}
