package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XExpression implements java.io.Serializable {
  public abstract <R,A> R accept(XExpression.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprOr p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprAnd p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.CondExprNot p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BoolExprRegex p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BoolExprRel p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprAdd p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprMultiply p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.ArithExprNeg p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprVar p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprCall p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprString p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprTrue p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprInt p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprDouble p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.BasicExprStmt p, A arg);

  }

}
