package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XOrderOption implements java.io.Serializable {
  public abstract <R,A> R accept(XOrderOption.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderOptionAsc p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderOptionDesc p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.OrderOptionEmpty p, A arg);

  }

}
