package stupaq.cloudatlas.query.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XRelOp implements java.io.Serializable {
  public abstract <R,A> R accept(XRelOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpEqual p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpNotEqual p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpGreater p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpGreaterEqual p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpLesser p, A arg);
    public R visit(stupaq.cloudatlas.query.parser.QueryLanguage.Absyn.RelOpLesserEqual p, A arg);

  }

}
