package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprAngle extends XExpression {
  public final ListXExpression listxexpression_;

  public BasicExprAngle(ListXExpression p1) { listxexpression_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprAngle) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprAngle x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprAngle)o;
      return this.listxexpression_.equals(x.listxexpression_);
    }
    return false;
  }

  public int hashCode() {
    return this.listxexpression_.hashCode();
  }


}
