package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprDouble extends XExpression {
  public final Double double_;

  public BasicExprDouble(Double p1) { double_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprDouble) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprDouble x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprDouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
