package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BasicExprCall extends XExpression {
  public final String xident_;
  public final ListXExpression listxexpression_;

  public BasicExprCall(String p1, ListXExpression p2) { xident_ = p1; listxexpression_ = p2; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprCall) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprCall x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BasicExprCall)o;
      return this.xident_.equals(x.xident_) && this.listxexpression_.equals(x.listxexpression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.xident_.hashCode())+this.listxexpression_.hashCode();
  }


}
