package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BoolExprRelNGT extends XExpressionNGT {
  public final XExpressionNGT xexpressionngt_;
  public final XRelOpNGT xrelopngt_;
  public final XExpression xexpression_;

  public BoolExprRelNGT(XExpressionNGT p1, XRelOpNGT p2, XExpression p3) { xexpressionngt_ = p1; xrelopngt_ = p2; xexpression_ = p3; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpressionNGT.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRelNGT) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRelNGT x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRelNGT)o;
      return this.xexpressionngt_.equals(x.xexpressionngt_) && this.xrelopngt_.equals(x.xrelopngt_) && this.xexpression_.equals(x.xexpression_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.xexpressionngt_.hashCode())+this.xrelopngt_.hashCode())+this.xexpression_.hashCode();
  }


}
