package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BoolExprRel extends XExpression {
  public final XExpression xexpression_1, xexpression_2;
  public final XRelOp xrelop_;

  public BoolExprRel(XExpression p1, XRelOp p2, XExpression p3) { xexpression_1 = p1; xrelop_ = p2; xexpression_2 = p3; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRel) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRel x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRel)o;
      return this.xexpression_1.equals(x.xexpression_1) && this.xrelop_.equals(x.xrelop_) && this.xexpression_2.equals(x.xexpression_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.xexpression_1.hashCode())+this.xrelop_.hashCode())+this.xexpression_2.hashCode();
  }


}
