package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class BoolExprRegexNGT extends XExpressionNGT {
  public final XExpressionNGT xexpressionngt_;
  public final String string_;

  public BoolExprRegexNGT(XExpressionNGT p1, String p2) { xexpressionngt_ = p1; string_ = p2; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpressionNGT.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRegexNGT) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRegexNGT x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolExprRegexNGT)o;
      return this.xexpressionngt_.equals(x.xexpressionngt_) && this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.xexpressionngt_.hashCode())+this.string_.hashCode();
  }


}
