package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class CondExprNotNGT extends XExpressionNGT {
  public final XExpressionNGT xexpressionngt_;

  public CondExprNotNGT(XExpressionNGT p1) { xexpressionngt_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XExpressionNGT.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.CondExprNotNGT) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.CondExprNotNGT x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.CondExprNotNGT)o;
      return this.xexpressionngt_.equals(x.xexpressionngt_);
    }
    return false;
  }

  public int hashCode() {
    return this.xexpressionngt_.hashCode();
  }


}
