package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public class Program extends XProgram {
  public final ListXStatement listxstatement_;

  public Program(ListXStatement p1) { listxstatement_ = p1; }

  public <R,A> R accept(stupaq.cloudatlas.parser.QueryLanguage.Absyn.XProgram.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof stupaq.cloudatlas.parser.QueryLanguage.Absyn.Program) {
      stupaq.cloudatlas.parser.QueryLanguage.Absyn.Program x = (stupaq.cloudatlas.parser.QueryLanguage.Absyn.Program)o;
      return this.listxstatement_.equals(x.listxstatement_);
    }
    return false;
  }

  public int hashCode() {
    return this.listxstatement_.hashCode();
  }


}
