package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XArithOpMultiply implements java.io.Serializable {
  public abstract <R,A> R accept(XArithOpMultiply.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.ArithOpMultiply p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.ArithOpDivide p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.ArithOpModulo p, A arg);

  }

}
