package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XBoolConst implements java.io.Serializable {
  public abstract <R,A> R accept(XBoolConst.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolConstTrue p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.BoolConstFalse p, A arg);

  }

}
