package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XNullsOption implements java.io.Serializable {
  public abstract <R,A> R accept(XNullsOption.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.NullsOptionFirst p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.NullsOptionLast p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.NullsOptionEmpty p, A arg);

  }

}
