package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XOrderClause implements java.io.Serializable {
  public abstract <R,A> R accept(XOrderClause.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.OrderClause p, A arg);
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.OrderClauseEmpty p, A arg);

  }

}
