package stupaq.cloudatlas.parser.QueryLanguage.Absyn; // Java Package generated by the BNF Converter.

public abstract class XOrderItem implements java.io.Serializable {
  public abstract <R,A> R accept(XOrderItem.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(stupaq.cloudatlas.parser.QueryLanguage.Absyn.OrderItemCond p, A arg);

  }

}
